---
- name: Add a jenkins group
  group:
    name: jenkins
    state: present
  become: true

- name: Add a jenkins user
  user:
    name: jenkins
    group: jenkins
    state: present
  become: true

- name: Create Swarm directory
  file:
    path: "{{ jenkins_swarm_path }}"
    state: directory
    mode: 0755
  become: true

- name: Download the Jenkins Swarm Client
  get_url:
    url: "{{ client_source }}"
    dest: "{{ jenkins_swarm_path }}"
    owner: jenkins
  become: true
  notify:
    - Restart Swarm Client service
  register: swarm_jar
  tags:
    - config

- name: "Ensure folders folder exists"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: true
  with_items:
    - "{{ jenkins_swarm_systemd_path }}"
    - "{{ jenkins_swarm_path }}"
  tags:
    - config

- name: "Ensure {{ jenkins_agent_labels_file }} file exists"
  file:
    path: "{{ jenkins_agent_labels_file }}"
    state: touch
    mode: 0755
  become: true
  when: jenkins_agent_labels_file is defined
  notify: Restart Swarm Client service
  tags:
    - config

- name: Ensure {{ jenkins_agent_labels_file }} contains defined labels
  lineinfile:
    path: "{{ jenkins_agent_labels_file }}"
    line: "{{ jenkins_agent_labels }}"
  become: true
  when: 
    - jenkins_agent_labels_file is defined
    - jenkins_agent_labels is defined
  notify: Restart Swarm Client service
  tags:
    - config

- name: Install default-jre from repository
  apt:
    name: default-jre
    state: present
  become: true

- name: Create the Swarm Client service def
  template:
    src: swarm-client.service.j2
    dest: "/lib/systemd/system/{{ jenkins_swarm_service_name }}.service"
    mode: 0755
  become: true
  notify:
    - Reload Systemd
    - Restart Swarm Client service
  tags:
    - config
